# Generated by Django 3.2.4 on 2022-03-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('category', models.CharField(choices=[('CA', 'Canvas Art'), ('S', 'Sculpture'), ('WC', 'Wood craft'), ('MI', 'Musical instrument'), ('H', 'Handicraft'), ('A', 'Antique'), ('S', 'Statue'), ('P', 'Painting'), ('MA', 'Mithila Art')], max_length=2)),
                ('slug', models.SlugField()),
                ('descreption', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
